-- Drop table to reset schema
DROP TABLE IF EXISTS quotations;

-- Create quotations table
create table if not exists quotations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Basic Info
  customer_id bigint references customers(id),
  product_id uuid references products(id),
  customer text,
  product_name text,
  category text,
  qty numeric,
  date date,

  -- Dimensions
  size_h numeric,
  size_w numeric,
  gsm numeric,
  rate_kg numeric,

  -- Paper
  ups_sheet numeric,
  paper_order numeric,
  buffer_qty numeric,

  -- Printing
  colour numeric,
  printing_ups numeric,
  printing_rate numeric,
  print_size_h numeric,
  print_size_w numeric,

  -- Finishing
  aqua_rt numeric,
  punch_rate numeric,
  punching_rt numeric,
  punch_cost numeric,
  plate_rate numeric,
  pasting_rate numeric,
  foil_pc numeric,

  -- Other Costs
  extra_cost numeric,
  packing_rate numeric,
  interest_pc numeric,
  profit_pc numeric,

  -- Calculations (Totals)
  amount_per_sheet numeric,
  paper_qty numeric,
  paper_cost numeric,
  paper_wt numeric,
  packing_amt numeric,
  printing_qty numeric,
  printing_amt numeric,
  aqua_amt numeric,
  punching_amt numeric,
  plate_amt numeric,
  pasting_amt numeric,
  foil_amt numeric,
  subtotal numeric,
  interest_amt numeric,
  profit_amt numeric,
  total_amt numeric,
  rate_pcs numeric,

  -- Per Piece Breakdown
  subtotal_pcs numeric,
  paper_pcs numeric,
  printing_pcs numeric,
  plate_pcs numeric,
  coating_pcs numeric,
  punching_pcs numeric,
  punch_rate_pcs numeric,
  pasting_pcs numeric,
  foil_pcs numeric,
  profit_pcs numeric,
  punch_only_pcs numeric,
  interest_pcs numeric,
  packing_pcs numeric,
  extra_pcs numeric
);

-- Enable RLS
alter table quotations enable row level security;

-- Create Policy for open access (adjust as needed for auth)
create policy "Enable all access" on quotations for all using (true) with check (true);
